name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o pocketbase-calendo

      - name: Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Delete the release and tag if they exist
          gh release delete latest --yes || true
          git push --delete origin latest || true
          
          # Create new release
          gh release create latest \
            --title "Latest Build" \
            --notes "Automated build from master branch" \
            pocketbase-calendo 